### ISSUE TITLE
Errors from d3 in frontend console output

### ISSUE THREAD

**Issue by theq629** [sfu-natlang/lensingwikipedia#108]
In #92 @anoopsarkar reports three apparently d3 related errors in the console:
> - event.returnValue is deprecated. Please use the standard event.preventDefault() instead
> - on mouseover in map over cluster: Uncaught ReferenceError: a is not defined
> - on zoom into map: Error: Problem parsing d=""

Of these:
- Might have been introduced in the previous d3 upgrade (#96), I'm not sure yet.
- Turned out to just be a typo in code I added recently, presumably for #106 . Fixed in mwhitneycleanup.
- Is a long-standing issue that doesn't seem to cause any problems. I suspect it might be associated with drawing to fast.

I am also noticing this error:
- Uncaught InvalidStateError: Failed to execute 'inverse' on 'SVGMatrix': The matrix is not invertible.

I also notice a flicker in the map view in some cases of toggling a reference point marker on the map view. This might be associated with the InvalidStateError. The InvalidStateError is happening inside mouse handling code. I had previously thought there was a flicker associated with the first of @anoopsarkar's points, and I'm not sure now if that's separate or the same (in which case I was probably thinking of the wrong error message).

**Comment by anoopsarkar** [comment]
Can we close this?

**Comment by theq629** [comment]
I think so, none of the errors seem to matter for now.
