### ISSUE TITLE
gitflow model

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#110]
we should probably follow the following model for git branching:
http://nvie.com/posts/a-successful-git-branching-model/

any thoughts?

**Comment by theq629** [comment]
From discussion in person, it might be useful to have separate stable and working branches. However it's not clear if it's actually worth the trouble at this point.

**Comment by anoopsarkar** [comment]
Probably better to have a testing version deployed on the web server but rather than having a testing branch in git it is probably better to pull the branch being tested and deploying it on port 9000 on natlang-web.

I'm closing this issue.
