### ISSUE TITLE
Add tSNE as a new navigation method

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#112]
Integrate tSNE 2D and 1D maps into lensingwikipedia. Make each cluster interactive with brushing showing more information, and clicking adding a new constraint. Let us start with a single pre-clustered interactive canvas and consider moving on to dynamically generated tSNE plots once we have the pre-clustered version working.

**Comment by KonceptGeek** [comment]
It's enabled for this release. Will add the toggle in frontendsettings.js in the next release.

**Comment by anoopsarkar** [comment]
actually I think it is more complex than just modifying frontendsettings.js due to the domain makefiles (ask Max what to do)

**Comment by anoopsarkar** [comment]
We need to add a progress indicator after the following step:

    Executing bh-tSNE

**Comment by anoopsarkar** [comment]
tSNE is now live on the website!

**Comment by anoopsarkar** [comment]
When I clear the constraint the selection bounding box remains active in the cluster map view.

**Comment by anoopsarkar** [comment]
Also, can we only show the points that are valid after a constraint is added? e.g. if we add "Person: Ptolemy" using Facets, then only 299 records should be visible (the actual number of points can be less than or equal to 299).

**Comment by KonceptGeek** [comment]
I'll work on those for the next build. I was thinking about doing that by running tSNE again on points that are valid after a constraint is added (using Facet, Timeline or Map view). Should we do a client side browser based tSNE execution or server side tSNE execution? Also, it currently only supports Chrome browser. Performance is extremely bad on Firefox. On Safari, the selection box is not drawn correctly.

**Comment by anoopsarkar** [comment]
see how the map does it. the clusters are computed once and served from the backend. a selection is handled on the client side by simply graying out points and making them impossible to select. however, this has to be implemented in a way that does not have to iterate over all points. 

is the cross browser problem due to d3 or something else? would the move to webgl help or hurt?

**Comment by anoopsarkar** [comment]
@KonceptGeek please create a new issue with a list of enhancements to the Cluster view and close this one.

**Comment by KonceptGeek** [comment]
tSNE has been added and enhancement issue has been created - https://github.com/sfu-natlang/lensingwikipedia/issues/136
