### ISSUE TITLE
Modules for javascript files

### ISSUE THREAD

**Issue by theq629** [sfu-natlang/lensingwikipedia#120]
Given that some of the javascript files are fairly large, I'd like to move to using some sort of modules, probably just the anonymous closure kind like
```
var mymodule = (function () {
  function foo() {
  }
  function bar() {
  }
  return {
    foo: foo
  }
}());
```

Does anyone have any objections or other ideas?

**Comment by theq629** [comment]
Would this be a convenient time for me to do the basic modules (not any serious refactoring, just modules for namespsaces)? It won't be a very significant change but it will touch a lot of code (ie all cross-file function calls).

**Comment by anoopsarkar** [comment]
yes, let's do modules and then take a look at `queries.js`

**Comment by theq629** [comment]
In the mwhitneyrefactoring branch I've added the simple modules as above. Modules names start with uppercase to avoid conflicts with existing variable names. I've adjusted function names to remove redundancies now that there are namespaces (eg setupMap() becomes Map.setup()). I did other minor renaming and the change for #138, but no other refactoring yet.

Configuration variables are now in the FrontendConfig module. The domain files (eg wikipediahistory_config_defaults.js) should define this module normally, and the installation settings (eg frontendsettings.js) can modify it.

I wasn't able to work out what to do in the Cluster tab that doesn't take too long for the backend to respond, so that part isn't tested properly.

How does this seem?

**Comment by anoopsarkar** [comment]
This sounds good to me but perhaps either @konceptgeek or @vlad003 can do a quick code review?

**Comment by vlad003** [comment]
I looked through the commits, and it looks great :+1: 

If there are any other things that need to be renamed, we can do that as we go. It should be easier now that most of the functions are isolated.

**Comment by theq629** [comment]
Yes, I'm thinking we can now work on improving each view component separately (but hopefully coming up with better patterns and shared code). I'm planning start with improving the facet view because I would like to share code with the storyline for #141.

**Comment by KonceptGeek** [comment]
Went through the commits and it looks good :+1:

**Comment by anoopsarkar** [comment]
Should we close this issue now?

**Comment by theq629** [comment]
Yes.
