### ISSUE TITLE
Comparison view

### ISSUE THREAD

**Issue by vlad003** [sfu-natlang/lensingwikipedia#122]
This issue is to keep track of my progress on the comparison view.

Features

- [x] select a facet, and it'll show a plot of the top 5 things from that fact using yearly counts
  - Doesn't require anything to be selected in the facet
- [x] Select another facet and update the plot
- [ ] Make it faster when there are a lot of data points (e.g. when selecting Category facet, the top one has 36k events).
- [x] Proper legend for each line
  - Currently it adds a name at the end of the line, but that gets cut off and and the names overlap
- [x] Click on names to show/hide them from the plot
- [ ] Query for specific names (rather than just top 5 from facet)
- [x] Zoom (similar to the timeline view)
- [x] Select 0, 1, all (number of things to show from facet)
- [ ] Show names on top points of graph **(dropped)**
- [x] Scale when zooming
- [x] Spacing of controls at the top
- [x] Show real counts, not smoothed counts (for legend)
- [x] Keep brush to the same domain when smoothing.
- [x] Move legend to the side 
- [x] Bold lines on hover

All work is in the ngram branch.

**Comment by anoopsarkar** [comment]
I think we can merge the ngram branch without the 3rd and 6th features above. If you are happy with the functionality and it is reasonably responsive we can merge.

**Comment by vlad003** [comment]
I still have one small bug where the lines are drawn a bit outside of the plot. I've been trying to fix it, but I don't see why it's not working; I'm doing the exact same thing as several examples online (which work fine).

@theq629 If you've got some time, do you think you could take a look at the branch to see if I'm using `clip-path` incorrectly? I'm using it the same as in the Timeline tab, but it's somehow not working for me. The browser's detecting the target properly, but it's ignoring the size/shape for whatever reason...

**Comment by vlad003** [comment]
Nevermind, it works now! I'll clean it up and then we can probably merge it.

**Comment by vlad003** [comment]
@anoopsarkar Other than the names showing up at the top of each line, everything else works properly. I haven't implemented the names thing because it would end up being pretty slow, and I think it'd end up being more difficult to use.

The main issue is that currently, the user can click on a name to make the line disappear from the graph (thus cleaning it up if you're only interested in a small time period, and one of the lines is causing everything to be scaled down). If we put the name on the plot, then it'd have to disappear when it's clicked, so the user wouldn't be able to bring the line back.

Secondly, it'd be more difficult to show the number of events; the legend shows the raw number of events for that year, while the plot shows smoothed values (which because of interpolation are even less accurate). Having tooltips would make the graph look inaccurate and obscure part of the plot. I think a legend separate from the plot is the best solution.

I can still try to implement it, but I can't think of a design which keeps it fast and usable :confused:

**Comment by anoopsarkar** [comment]
Currently, how do we know which line corresponds to which entity? Is it based on the legend and matching the color from the legend to the plot?

**Comment by vlad003** [comment]
@anoopsarkar I think this feature's done. I want to look into speeding it up, but otherwise the interface is functional; I've implemented the modifications we talked about on Monday (bolded lines, legend on the right, improved spacing in the controls).

If you find a bug, I can work on fixing it tomorrow (or technically today - Wednesday Feb 4).

**Comment by anoopsarkar** [comment]
Let us live dangerously. Can you send me a pull request.

**Comment by vlad003** [comment]
I just realized there are some merge conflicts with master I have to resolve before doing a pull request. I didn't realize we reverted to the old way of creating the tags (i.e. revert from using a function to writing the HTML ourselves).
