### ISSUE TITLE
User accounts and saving queries

### ISSUE THREAD

**Issue by vlad003** [sfu-natlang/lensingwikipedia#125]
The site currently has no user accounts, and it could be useful for users to be able to create an account to manage their settings, save/load queries and keep track of sessions.

## Use cases

1. User creates some queries and wants to save them so he can close the browser and come back to them later. If the queries are simple, the user can recreate them, but if they're more complicated the user would currently have to write down the constraints.
2. User wants to create a new query, but would like to save the current query so she can compare the two later. It would be inconvenient (and likely slower) to require two separate windows/tabs to be opened for the two queries.
3. User has created several related queries that they'd like to save so she can reference them later. This could be considered a "session".
4. User has created an interesting set of queries (or session) that they'd like to share with another user. The receiver might have an account on the site or he might not.

## What's done so far

I've already implemented saving and loading queries in the `query-management` branch (although there are some issues). It can currently save the constraints and load them, but all the watchers are lost. With further work on the query module, this can definitely be made more robust.

I've implemented user accounts with email/password and account data several times so I can repurpose a lot of my existing code to create the these features.

## What would need to be done

* Decide if this is a useful feature to implement.
* Improve the query module to allow more robust saving and loading of queries
  * Most importantly, there needs to be a way to recreate watchers. This will probably require an API change because right now all the views will create a new watcher when they're loaded.
* Come up with a secure way of saving all this data to avoid XSS issues.
* Figure out if we want user accounts at all, or if we want to get users to save their sessions to files. It could be the exact same stuff that's saved to the database except users would keep track of the data. For sharing we could get users to send their session file to another user, or click a "Share" button that would generate a unique URL for the session (meaning we'd save the session in a database).

Any ideas / suggestions?

**Comment by theq629** [comment]
Does it seems like the current queries.js interface will work well enough for restoring queries (especially the recreating watchers thing), or do we need to consider any major changes there?

**Comment by vlad003** [comment]
It mostly works for restoring constraints, but watchers can't be recreated by queries.js. Check out this commit: 57169144197f6ec7c8e43c4dcbe4e2ae7582ee14

I think restoring watchers is doable without modifying the interface, but it would require changes from users of the interface. I think the best way would be for users of queries.js to recreate their own watchers based on the existing constraints, rather than the current method of creating a new one when setupX() is called. The queries.js code wouldn't be able to do this because of all the closures.

**Comment by anoopsarkar** [comment]
user accounts can be treated largely orthogonal to saving queries, IMO.

perhaps a change in queries.js could be considered first which would
eventually fit in better with a user account to save those queries along
with other information about user browsing.

**Comment by vlad003** [comment]
Since we're scrapping this idea, I'll close the issue. Check for references to this issue for ideas that supersede this one.
