### ISSUE TITLE
smoothing level zero in new Timeline

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#132]
My impression of smoothing level zero was that it would look identical to the version we replaced with the new Timeline. It does not seem to do that.

**Comment by vlad003** [comment]
Smoothing 0 means the data isn't smoothed in any way, but it's still displayed using the same style of line graph.

I can switch it to a histogram (like it was before) if that would be better.

**Comment by anoopsarkar** [comment]
we can add a "None" which does the histogram.
