### ISSUE TITLE
cache all queries in backend

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#135]
I was talking with Andrei and the issue of caching all query results was raised. We could use memcache on the server to cache results from whoosh query. Any LRU eviction scheme (as in memcached) would work fine I think.

**Comment by anoopsarkar** [comment]
Can this be done as an extension of Issue #125?

**Comment by vlad003** [comment]
The backend will still end up having to query memcached itself. I can wrap the queries to the backend to go through the Flask backend, but I'm not sure if there's much benefit to doing that (although if we want to clean up the codebase it'd be a good idea to have Flask handle all of the HTTP stuff).

**Comment by anoopsarkar** [comment]
Cleaning up the codebase would be a good idea. As long as the code is modular so that the backend can be connected to another framework easily then having flask handle everything would be good.

**Comment by vlad003** [comment]
This is fixed in the `develop` branch.
