### ISSUE TITLE
multiple Person facets: what would happen?

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#138]
For some reason if I add multiple Person facets to the Facet view, what would happen?

Would I be able to select different entities from each of the Person facets, or would they be linked somehow via queries.js?

**Comment by theq629** [comment]
I think the main facet code would handle it fine, and they would be unlinked. However, the list of facets (in index.html) is keyed on field, and storyline.js may also make that assumption. So we'd need to change that to be able to do this at all.

**Comment by theq629** [comment]
In the mwhitneyrefactoring branch the list of facets is not keyed on field, so you can add duplicates easily. For example put this in frontendsettings.js for an extra person facet that the storyline will ignore.
```
FrontendConfig.facets.push({
  field: "person",
  title: "Person2"
});
```

**Comment by anoopsarkar** [comment]
Great. I assume this means that we can use this functionality for issue #141 

Should we close this issue?

**Comment by theq629** [comment]
The branch also includes the changes for #120 (which may need feedback before merging), so whatever you think about closing this issue.
