### ISSUE TITLE
Restarting the backend server after a crash 

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#139]
Is it worth adding a server auto-restart on crash?

**Comment by KonceptGeek** [comment]
As discussed yesterday, we could add a quick hack so that the backend keeps updating a file every minute and a shell script could keep checking if the file is being updated, otherwise it would kill the backend and restart again.

**Comment by vlad003** [comment]
Can't we get the init system to do it? CentOS uses Upstart, doesn't it?

**Comment by theq629** [comment]
Note that the backend should already allow crashes inside the query handling code without crashing the whole server. So the main issue is probably timing out queries rather than crashes. (Although external support would be a good idea as well.)

**Comment by anoopsarkar** [comment]
I'm looking for:
1. a small footprint (not much change to the existing code)
2. not much maintenance (no need to check often if the restart procedure itself is working)
3. easy to deploy on standard platforms

init.d or upstart or systemd might be suitable. This is a common enough problem that there should be a recipe somewhere, right?

**Comment by vlad003** [comment]
You'd only need something simple like this for Upstart:

    start on runlevel 2
    exec $BACKEND -c full.conf
    respawn

**Comment by anoopsarkar** [comment]
Andrei can you check if natlang-web has upstart? I suspect it is still
init.d

If it isnt already installed and if it can be installed via yum, then I can
do it. Let me know.

**Comment by KonceptGeek** [comment]
Isn't Upstart for starting application when the system is started? I thought we wanted a solution when the application crashed due to large queries.

**Comment by vlad003** [comment]
Upstart can handle starting services whenever you want, including manually. The `respawn` statement tells it to restart the service when it crashes.

**Comment by vlad003** [comment]
@anoopsarkar according to yum, the upstart package is installed.

**Comment by anoopsarkar** [comment]
I tried various ways to get upstart to launch and respawn the backend and failed.

Perhaps I can sit with @vlad003 and do this with him.

**Comment by anoopsarkar** [comment]
@vlad003 could you get upstart working on natlang-web.cs.sfu.ca? If you did, send me a shell file to execute that will get the backend running using upstart.

**Comment by vlad003** [comment]
Could I get sudo access on that server? I need it to write and run the .conf files in /etc/init.

**Comment by anoopsarkar** [comment]
Since the dockerize PR #192 was merged with master we no longer use upstart.
