### ISSUE TITLE
What's the difference between the avherald and wikipediahistory domains?

### ISSUE THREAD

**Issue by vlad003** [sfu-natlang/lensingwikipedia#147]
Are there significant changes in the code between the two, or can the differences be handled by a config file?

I need to get rid of the Makefiles and get my Flask code figure out which JS and CSS files to serve. If the differences are only in the config files, I can have a variable in Flask's config.py to choose what to serve (which would greatly simplify everything).

**Comment by theq629** [comment]
The differences are all in config files, but all the config files are regular code.

The current makefile system for the frontend allows adding to or changing the lists of Javascript and CSS to include in the build. That means that we could for example have a domain-specific view with its own javascript file and changes to index.html. But right now we don't do anything like that, and both domains basically use different versions of the same few files (with some domain-specific filename affixes that could be changed).
