### ISSUE TITLE
Experimental facet code refactoring

### ISSUE THREAD

**Issue by theq629** [sfu-natlang/lensingwikipedia#151]
Extracting the list box code out of the facet code for #141 can be an opportunity to experiment with refactoring at least part of the facet code.

(This was going to be done along with #141, but it looks like #141 will probably be resolved with duplicated code remaining.)

**Comment by anoopsarkar** [comment]
Once this issue is resolved we can add Facet constraints using the Storyline view and/or the Facet view and they can inter-operate unlike the behaviour currently.

**Comment by theq629** [comment]
I've pushed the refactored facet code to mwhitneyrefactoring. Most of the code is now shared by the facets and the drop down in the storyline view. We could easily add a search box to the later now too. I'm not sure how well I like the OO-syle code I have right now, but it's definitely an improvement over the original facet code.

**Comment by theq629** [comment]
I haven't changed anything in the storyline view yet (for adding facet constraints), but if you'd like that added it should be easier now.

**Comment by anoopsarkar** [comment]
If you are done with refactoring then we can go ahead with adding Facet constraints in the Storyline view for each selection done in that view.

**Comment by anoopsarkar** [comment]
We can merge these changes with master and close this issue before we move on to improving the Storyline view to inter-operate with Facets.

**Comment by theq629** [comment]
Ok, I'll make a new issue for the facet constraints and a pull request for this one.

**Comment by theq629** [comment]
Also, if anyone has comments on the new code then let me know. We could consider doing something similar for other views.
