### ISSUE TITLE
Clear selection does nothing in Storyline view

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#154]
In the current Storyline view (with the entity selection in the view itself) the 'Clear Selection' button does not clear the currently selected entities.

**Comment by theq629** [comment]
It's working for me on the live site. It should clear constraints added by the storyline.

**Comment by anoopsarkar** [comment]
I see. If I select many entities using the drop down menu, I would like to clear them all. Not sure how to do this. I ca. see it would be confusing to use the same button.

**Comment by theq629** [comment]
Well, we could definitely add another button to clear the view entities, but I'm also not sure what to call it. What about adding another "Clear" button inside the dropdown itself, above the list of entities?

I agree that the current "Clear selection" is confusing, but it's the same name used for the other views, so we should probably leave it or change them all. We could maybe rename them all to "Clear constraints".

**Comment by KonceptGeek** [comment]
It doesn't work work until unless you choose a person from facet view once.
The clear selection wouldn't work anywhere until this has been done.

Regards,

Jasneet Sabharwal
*AboutMe - http://about.me/jasneetsabharwal
<http://about.me/jasneetsabharwal>*

**Comment by KonceptGeek** [comment]
The Clear Selection button only works once you have selected a constraint from facet view. Once this is performed, the Clear Selection can then be used in any view.

**Comment by anoopsarkar** [comment]
For now, I like the idea of having another button inside the dropdown above the list of entities.

@KonceptGeek only constraints can be cleared, but Storyline has another modality of entities that can be selected using the drop down list (which are not treated as constraints; at least not yet).

**Comment by theq629** [comment]
I've added the new clear button in my demos and the mwhitneyrefactoring branch. I haven't had time to test it too much, so if you merge it before the demo please check that it does work for what you want.

**Comment by theq629** [comment]
On thinking more about the name of the "Clear selection" buttons: I think it does have the potential to be confusing like it this case, but it's often disambiguated by the interface. Renaming to "Clear constraints" would be consistent with "Clear all constraints" button in the top left, but to me is less clear that it's specifically the constraints made from selections in the current view.

Maybe a better option would be to aim to make all constraint-related buttons visually similar through placement, colours (very early on I had a plan to use colours that way, but it's not at all consistent now), and perhaps later small icons.

**Comment by anoopsarkar** [comment]
can you do a pull request for this and that will close this issue for now.
