### ISSUE TITLE
Clear selection remains highlighted

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#160]
The `Clear selection` button in the Facet view remains highlighted after `Clear all constraints`.

e.g. select a Location, say Egypt. click on `Clear all constraints`. The `Clear selection` button remains highlighted. You can click on it to switch back to the unselected color.

**Comment by vlad003** [comment]
Has this been fixed? I just checked on master, and I'm not seeing the bug anymore.

**Comment by anoopsarkar** [comment]
I still see this bug on Chrome (macosx)

**Comment by vlad003** [comment]
I see it on http://lensingwikipedia.cs.sfu.ca:8080, but not on the latest code on master. Has the site been updated?

**Comment by anoopsarkar** [comment]
Probably has not been updated in a while.

**Comment by anoopsarkar** [comment]
Fixed in current master as a corollary of other bug fixes.

Closing.
