### ISSUE TITLE
The + button is hidden

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#198]
The `+` button that expands the text on the left side column to show the entire event description is currently not showing up or is transparent. One can still click on where the `+` should appear and it will show the entire event. Perhaps it a CSS issue? 

To replicate this bug: Select `Augustus` from the Person facet and click to the space next to the period on the first event on the left hand panel.

**Comment by anoopsarkar** [comment]
I give up. I tried to put in the new glyphicons css into wikipediahistory.js and avherald.js 

I added the fonts files to vendor/bootstrap/fonts 

These changes are in master. Now I can't even click on the space to toggle the full description. Perhaps it does not like the combination of using `"glyphicon glyphicon-plus-sign"`and the use of `toggleClass`.

**Comment by vlad003** [comment]
It works fine for me (not on master, but on a branch that's derived from the latest commit to master)
![screenshot from 2015-08-28 13 39 05](https://cloud.githubusercontent.com/assets/631497/9556534/54e07a46-4d8a-11e5-9fb0-59cf6b8d4e32.png)

**Comment by vlad003** [comment]
This is fixed in a0fa4705f1126dd83a296ffe0cca5b6855f14eee.

**Comment by anoopsarkar** [comment]
There is a bug in the solution to this issue. Here is how to recreate it:

1. Go to http://lensingwikipedia.cs.sfu.ca:8080
1. Select `Muhammed` from Person
1. Select `Jabal Thawr` from Location
1. Repeatedly toggle `[+]` to `[-]` and vice versa in the last event with heading `622 CE: warn`. You should be able to see both `[+]` and `[-]` and also part of the description gets hidden.

It might have something to do with the line break in the middle of `[+]`.

**Comment by vlad003** [comment]
It seems to work as expected for me. Clicking `[+]` expands the description, and `[-]` hides it.

**Comment by anoopsarkar** [comment]
In my browser (Chrome macosx) it sometimes hides the first half of the description and also shows both `+` and `-` in some cases.

**Comment by vlad003** [comment]
That seems like a bug in Chrome, rather than in my code. All the code does is replace the text within a tag; it doesn't touch anything else.

**Comment by vlad003** [comment]
Replacing the `.html()` with `.text()` doesn't seem to help, but I'll make that change anyways since it's better.

**Comment by anoopsarkar** [comment]
Works fine on Safari on macosx. So a Chrome issue then. I'll re-close the issue.
