### ISSUE TITLE
facet counts not being updated

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#200]
Recent changes to facet handling has broken count updates.

To recreate bug with just Facet:

1. Select any entity in Person facet
1. Notice that the numbers do not change for the other entities. Selection is now intersection so the counts should reflect that.

To recreate bug with Storyline and Facet:

1. Select 'Hadrian' in Person facet
1. Select 'Hadrian' in Storyline facet
1. Select 'Vibia Sabina' in the Storyline entity line 
1. Go back to Facet tab. The counts are clearly incorrect.

**Comment by theq629** [comment]
I believe this is working properly on my demo site (http://lensingwikipedia.cs.sfu.ca:9000) now, for both facet and storyline. Please check. I'm not totally sure that the second counts bug is the same as the first bug, but most likely it is and therefore both are fixed.

**Comment by anoopsarkar** [comment]
Yes, it is working. Can you push this fix to master please. The main site is essentially broken without this fix.

**Comment by theq629** [comment]
Ok, pushed to storyline fixes with a pull request to master.
