### ISSUE TITLE
Facet dropdown list in Storyline view inconsistent with main Facet list

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#202]
The dropdown list of entities in the Storyline view is not consistent with the selections made in the Facet tab.

**Comment by theq629** [comment]
This will basically revert the decoupling part of  #141, won't it? I think that is a good idea since the current behavior is confusing, I just want to make sure I understand before I change it.

And to note here, we've decided to keep the update button. Did we also decide to keep the dropdown for now?

**Comment by anoopsarkar** [comment]
Yes, we first decoupled it and then kinda coupled it in another issue: #168 

Also, it would be good to first fix the facet bug #200 before you fix this issue.

**Comment by theq629** [comment]
Oh, that's right, in #168 we changed this around.

Yes, let's do #200 and #201 first. Do you want this one changed immediately after if I have time, or is it better to wait for after the demo anyway in case we end up with further changes to make?

**Comment by anoopsarkar** [comment]
Now the dropdown list is consistent with the main Facet list so this is less urgent. Let us first do a PR for #200 and #201 and this issue can also be closed, right? We can open a new issue about the nature of the coupling of Facet and Storyline views or we can debate about doing it more like the Comparison view (which seems more decoupled than Storyline).

**Comment by theq629** [comment]
Ok, we can close this and come back to the coupling issue if it's ok for now. I was thinking if we do switch back to having the storyline couple more strongly with the facet while keeping the dropdown, then maybe we should consider having the comparison view use the same sort of dropdown.

**Comment by anoopsarkar** [comment]
Ok. Can you close up any resolved issues and old branches (I see a few branches related to storyline that have been merged with master already).

**Comment by theq629** [comment]
Ok, I've removed all my branches and closed resolved issues.

**Comment by anoopsarkar** [comment]
We can close this issue too?

**Comment by theq629** [comment]
Yes, if you think it's all right now then go ahead.
