### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by msiahbani** [sfu-natlang/lensingwikipedia#205]
I guess we should update the "About" page on lensingwikipedia: 
" After all of the data was processed we have about 20,000 predicates that we use in our visualization."
We have more that 80K predicates.

**Comment by anoopsarkar** [comment]
The About page has vanished in the current version:
http://lensingwikipedia.cs.sfu.ca:8080/

**Comment by vlad003** [comment]
I think I forgot to copy that file when I moved stuff over to Flask. I'll add it back now.

**Comment by vlad003** [comment]
This was fixed in PR #206.

I was hoping the PR merge would close the issue, but apparently you have to say "Fixes #X" not "Fixes issue #X".
