### ISSUE TITLE
Remove egregious bootstrap non-semantic classes

### ISSUE THREAD

**Issue by theq629** [sfu-natlang/lensingwikipedia#9]
Currently there are a bunch of bootstrap classes like btn-mini in use. This information is in the .js files and makes the styles non-obvious. We should probably duplicate the relevant bits of bootstrap css with more semantic names.

**Comment by anoopsarkar** [comment]
can we close this issue?

**Comment by anoopsarkar** [comment]
with the reorganization of the js code, can we close this issue?

**Comment by theq629** [comment]
The reorganization doesn't affect this. It's up to you if you think this matters or not, it was originally just my own goal. In any case, I'm not sure there is any easy way to get really semantic CSS classes with bootstrap short of either manually copying parts or using some extended CSS that compiles to real CSS.

**Comment by anoopsarkar** [comment]
Let's close it.

**Comment by theq629** [comment]
After trying to decide on the style for the button in #168 and considering that we are switching to flask, I'm actually reconsidering this. In terms of maintaining visual consistency it would help to be able to apply relevant css class to buttons and other visual elements. For example we could have a class for all constraint-related elements that would allow us to choose similar colours for them. I assume with flask we could add some sort of extended CSS that would allow derived classes (actually all we need for now is class aliases).

**Comment by vlad003** [comment]
I support using Less or Sass* instead of the plain Bootstrap CSS to style the frontend. It should clean up the HTML quite a bit, and we can get Flask (using some plugin) to compile the Sass code when it starts up. I've seen some plugins for doing this.

\* I vote for Sass
